name: Build e Teste Docker

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t site-html .

      - name: Rodar o container e testar
        run: |
          docker run -d -p 8080:80 --name site-container site-html
          sleep 10  # Aumentar o tempo de espera
          curl -I http://localhost:8080 || true
          
      - name: Ver logs do container
        run: docker logs site-container

      - name: Enviar alerta para Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"🚀 Build finalizado no GitHub Actions para o repositório $GITHUB_REPOSITORY - Status: ${{ job.status }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
